"""Create or verify MANIFEST.txt - every tracked file with its size and git blob hash.

Used to prove a copy of the project is byte-for-byte identical to the repository, even when the
files were transferred without git (e.g. recreated from the GitHub web view).

    On the source machine (needs git):       python tools/verify_manifest.py --create
    On the target machine (git NOT needed):  python3 tools/verify_manifest.py

Standard library only; works on Python 3.8+ (including the macOS system python3).
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "MANIFEST.txt"
BINARY_EXTENSIONS = {".ttf", ".otf", ".woff", ".woff2", ".png", ".jpg", ".jpeg", ".gif", ".ico", ".pdf", ".zip"}


def blob_sha1(data: bytes) -> str:
    """Same hash git uses for file contents (so it matches `git ls-tree` / GitHub)."""
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()  # noqa: S324 - integrity, not security


def create() -> int:
    raw = subprocess.run(
        ["git", "ls-tree", "-r", "-l", "-z", "HEAD"], cwd=ROOT, capture_output=True, check=True
    ).stdout
    rows = []
    for entry in raw.split(b"\0"):
        if not entry:
            continue
        meta, path_bytes = entry.split(b"\t", 1)
        _mode, kind, sha, size = meta.split()
        path = path_bytes.decode("utf-8")
        if kind != b"blob" or path == MANIFEST.name:
            continue
        rows.append(f"{sha.decode()}  {int(size):>8}  {path}")
    header = [
        "# MANIFEST - generated by tools/verify_manifest.py --create",
        "# Format: <git blob sha1>  <size in bytes>  <path>",
        f"# Files: {len(rows)}",
    ]
    with open(MANIFEST, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(header + rows) + "\n")
    print(f"Wrote {MANIFEST.name} with {len(rows)} files. Commit and push it together with the code.")
    return 0


def verify(strict: bool) -> int:
    if not MANIFEST.exists():
        print("MANIFEST.txt not found in the project root.")
        return 2
    ok, crlf, missing_text, missing_binary, mismatched = [], [], [], [], []
    for line in MANIFEST.read_text(encoding="utf-8-sig").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        sha, size, path = line.split(None, 2)
        target = ROOT / path
        is_binary = Path(path).suffix.lower() in BINARY_EXTENSIONS
        if not target.is_file():
            (missing_binary if is_binary else missing_text).append(path)
            continue
        data = target.read_bytes()
        if blob_sha1(data) == sha:
            ok.append(path)
        elif blob_sha1(data.replace(b"\r\n", b"\n")) == sha:
            crlf.append(path)
        else:
            mismatched.append((path, int(size), len(data)))

    total = len(ok) + len(crlf) + len(missing_text) + len(missing_binary) + len(mismatched)
    print(f"Checked {total} files: {len(ok)} identical")
    if crlf:
        print(f"\n{len(crlf)} file(s) have Windows (CRLF) line endings - convert to LF:")
        for p in crlf:
            print(f"  CRLF      {p}")
    if mismatched:
        print(f"\n{len(mismatched)} file(s) DIFFER from the repository - copy them again exactly:")
        for p, expected, actual in mismatched:
            print(f"  DIFFERENT {p}   (expected {expected} bytes, found {actual})")
    if missing_text:
        print(f"\n{len(missing_text)} text file(s) MISSING:")
        for p in missing_text:
            print(f"  MISSING   {p}")
    if missing_binary:
        print(f"\n{len(missing_binary)} binary file(s) missing (fonts/images cannot be copied as text):")
        for p in missing_binary:
            print(f"  BINARY    {p}")

    text_ok = not (crlf or mismatched or missing_text)
    if text_ok and (not missing_binary or not strict):
        print("\nALL TEXT FILES MATCH" + (" (binary files still to be provided)" if missing_binary else ""))
        return 0
    print("\nNOT YET COMPLETE")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--create", action="store_true", help="write MANIFEST.txt from the current git HEAD")
    parser.add_argument("--strict", action="store_true", help="also fail when binary files are missing")
    args = parser.parse_args()
    return create() if args.create else verify(args.strict)


if __name__ == "__main__":
    sys.exit(main())
